package org.example.lab2.mybatis.dao;

import org.example.lab2.mybatis.model.Team;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    int insert(Team row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    Team selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    List<Team> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    int updateByPrimaryKey(Team row);
}