package org.example.lab2.mybatis.model;

public class Team {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.ID
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.NAME
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.NUMBEROFMEMBERS
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    private Integer numberofmembers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM.SCORE
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.ID
     *
     * @return the value of PUBLIC.TEAM.ID
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.ID
     *
     * @param id the value for PUBLIC.TEAM.ID
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.NAME
     *
     * @return the value of PUBLIC.TEAM.NAME
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.NAME
     *
     * @param name the value for PUBLIC.TEAM.NAME
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.NUMBEROFMEMBERS
     *
     * @return the value of PUBLIC.TEAM.NUMBEROFMEMBERS
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public Integer getNumberofmembers() {
        return numberofmembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.NUMBEROFMEMBERS
     *
     * @param numberofmembers the value for PUBLIC.TEAM.NUMBEROFMEMBERS
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public void setNumberofmembers(Integer numberofmembers) {
        this.numberofmembers = numberofmembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM.SCORE
     *
     * @return the value of PUBLIC.TEAM.SCORE
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM.SCORE
     *
     * @param score the value for PUBLIC.TEAM.SCORE
     *
     * @mbg.generated Mon Mar 25 21:24:20 EET 2024
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}